# OpenRCT2 Touch iOS cross-compilation toolchain.

set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_VERSION 27.0)

set(OPENRCT2_IOS_PLATFORM "DEVICE" CACHE STRING "iOS target: DEVICE or SIMULATOR")
set_property(CACHE OPENRCT2_IOS_PLATFORM PROPERTY STRINGS DEVICE SIMULATOR)
string(TOUPPER "${OPENRCT2_IOS_PLATFORM}" OPENRCT2_IOS_PLATFORM)

if (OPENRCT2_IOS_PLATFORM STREQUAL "DEVICE")
    set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "" FORCE)
elseif (OPENRCT2_IOS_PLATFORM STREQUAL "SIMULATOR")
    set(CMAKE_OSX_SYSROOT iphonesimulator CACHE STRING "" FORCE)
else ()
    message(FATAL_ERROR "OPENRCT2_IOS_PLATFORM must be DEVICE or SIMULATOR")
endif ()

set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET 27.0 CACHE STRING "Minimum iOS version")

if (NOT CMAKE_Swift_COMPILER)
    set(CMAKE_Swift_COMPILER /usr/bin/swiftc CACHE FILEPATH "Swift compiler")
endif ()
if (OPENRCT2_IOS_PLATFORM STREQUAL "SIMULATOR")
    set(CMAKE_Swift_COMPILER_TARGET "arm64-apple-ios${CMAKE_OSX_DEPLOYMENT_TARGET}-simulator")
else ()
    set(CMAKE_Swift_COMPILER_TARGET "arm64-apple-ios${CMAKE_OSX_DEPLOYMENT_TARGET}")
endif ()

# Keep host packages out of target discovery. Dependencies are provided by the
# pinned vcpkg installation or an explicit CMAKE_PREFIX_PATH.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
